#!/usr/bin/env python3

# Author: Y.Takahashi, Hokkaido University
# Date: 2026/09/11
#
# 海岸線のテキストファイル（coastline_110m.txt）を作る。**一度走らせれば済む。**
#
#   python3 src_helper/general/generate_coastline.py
#
# 出所は Natural Earth の 1:110m coastline（パブリックドメイン。出典表示も不要と
# 明記されている）。ダウンロードした shapefile を、経度・緯度の折れ線のテキストに
# 落とす。可視化ツールが読むのはそのテキストだけなので、**実行時に外部ライブラリも
# ネットワークも要らない**（cartopy / shapely / pyproj を持ち込まないのはこのため）。
#
# shapefile の読み取りはここで完結させている（PolyLine だけなので 40 行ほど）。
# 形式: 100 バイトのヘッダ -> レコード（ヘッダ 8 バイト + 中身）の並び。
# PolyLine の中身は [型 int32, 外接矩形 double x4, パート数 int32, 点数 int32,
# パートの開始位置 int32 x n, 点 (x, y) double x m]（型と点はリトルエンディアン）。

import argparse
import io
import os
import struct
import sys
import urllib.request
import zipfile

URL_DEFAULT = 'https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_coastline.zip'
NAME_SHAPE  = 'ne_110m_coastline.shp'

SHAPE_POLYLINE = 3

HEADER = """# Coastline for the 3-D views of src_helper/
#
# --Source: Natural Earth, 1:110m physical / coastline (public domain).
#   {url:s}
# --Generated by src_helper/general/generate_coastline.py; do not edit by hand.
# --Format: one polyline per block, "longitude latitude" in degrees, one point per
#   line, blocks separated by a blank line. Read by src_helper/general/coastline.py,
#   which needs numpy and nothing else.
# --Polylines: {number_line:d}, points: {number_point:d}
"""


def argument():
  parser = argparse.ArgumentParser(description='Write the coastline text file.')
  parser.add_argument('-o', '--output', default=None,
                      help='output file (default: coastline_110m.txt next to this script)')
  parser.add_argument('--url', default=URL_DEFAULT, help='zipped shapefile to read')
  parser.add_argument('--zip', default=None,
                      help='use a zip already on disk instead of downloading it')

  return parser.parse_args()


def read_polyline_shapefile(content):
  #
  # shapefile（.shp）の中身から PolyLine を取り出し、[(経度, 緯度), ...] の並びで返す。
  #
  segment_list = []
  position = 100                                   # ファイルヘッダのあと
  while position < len(content) :
    number, length = struct.unpack('>ii', content[position:position+8])
    position = position + 8
    record   = content[position:position+2*length]  # 長さは 16 bit ワード数
    position = position + 2*length

    kind = struct.unpack('<i', record[0:4])[0]
    if kind != SHAPE_POLYLINE :
      print('Not a polyline shapefile, record', number, 'is of type', kind)
      sys.exit(1)

    number_part, number_point = struct.unpack('<ii', record[36:44])
    part  = struct.unpack('<{:d}i'.format(number_part), record[44:44+4*number_part])
    start = 44 + 4*number_part
    point = struct.unpack('<{:d}d'.format(2*number_point),
                          record[start:start+16*number_point])

    # パートごとに折れ線を切り出す
    index = list(part) + [number_point]
    for i in range(0, number_part) :
      line = [(point[2*k], point[2*k+1]) for k in range(index[i], index[i+1])]
      if len(line) > 1 :
        segment_list.append(line)

  return segment_list


def main():

  args = argument()

  if args.zip is not None :
    with open(args.zip, 'rb') as f:
      blob = f.read()
  else :
    print('Downloading...: ', args.url)
    with urllib.request.urlopen(args.url) as response:
      blob = response.read()

  with zipfile.ZipFile(io.BytesIO(blob)) as archive:
    name = [item for item in archive.namelist() if item.endswith(NAME_SHAPE)]
    if len(name) == 0 :
      print('The archive does not hold', NAME_SHAPE, ':', archive.namelist())
      sys.exit(1)
    content = archive.read(name[0])

  segment_list = read_polyline_shapefile(content)
  number_point = sum(len(line) for line in segment_list)
  print('Polylines: ', len(segment_list), ', points: ', number_point)

  filename = args.output
  if filename is None :
    filename = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'coastline_110m.txt')

  with open(filename, 'w') as f:
    f.write(HEADER.format(url=args.url, number_line=len(segment_list),
                          number_point=number_point))
    for line in segment_list:
      f.write('\n')
      for longitude, latitude in line:
        f.write('{:.4f} {:.4f}\n'.format(longitude, latitude))

  print('Written: ', filename, '({:.1f} kB)'.format(os.path.getsize(filename)/1024.0))

  return


if __name__ == '__main__':
  main()
