
computational_setup:
  # Flag for initial or restart calculation
  # --True: initial condition, False: restart
  flag_initial: True

  # Maximum time step, s
  time_elapsed_maximum: 5000.0


satellite: 
  # Mass, kg
  mass: 3.971
  # Characteristic area, m^2
  characteristic_area: 0.552
  # Characteristic length, m
  characteristic_length: 0.8

  # Aerodynamic model
  # --constant, or fileread
  kind_aerodynamic_model: fileread

  # Drag coefficient (aerodynamic_model: constant)
  drag_coefficient: 1.0

  # Drag coefficient (aerodynamic model: fileinput)
  directory_path_specify: default # default or manual
  directory_aerodynamic: ../../database/aerodynamic
  filename_aerodynamic: aerodynamic.txt


initial_settings:
  # Initial conditions 
  # Initial coordinate, 1:Long.(deg) 2: Lat.(deg), 3:Alt.(km)
  coordinate:
    - -156.79
    -  51.47
    -  201.58
  velocity:
    -  7577.57998256923
    - -262.224438463479
    -  3.45812245578943
  density_factor:
    - 1.0


planet:
  # Gravitational constant, M.m2/kg2
  gravitational_constant: 6.67408e-11
  # Planet mass (Earth), kg
  mass: 5.9723662e+24
  # Planet radius on Equator, m
  radius: 6.3781370e+6 
  # Ellipticity 
  ellipticity: 3.35281066474e-3
  # Rotation rate, rad/s
  rotation_rate: 7.292115e-5
  # Dynamic form factor (J2) for potential calculation
  potential_factor:
    J2: 1.082629e-3
    J22: -1.81222e-6
    J3: -2.5356e-6 
    J4: -1.62336e-6
    Lambda22: -14.545   # Degree
    

atmosphere:
  # Atmosphere model
  # --constant, or fileread
  kind_atmosphere_model: fileread

  # Atmosphere model: constant settings
  # Densitry, kg/m3
  density: 1.e-3
  # Temperature, K
  temperature: 300.0

  # Atmosphere model: file input
  directory_path_specify: default # default or manual
  directory_atmosphere: ../../database/atmosphere
  filename_atmosphere: atmospheremodel.txt

  
time_integration:
  # Time integration settings

  # Time marching scheme: 
  # --"explicit_euler", "implicit_lusgs"
  kind_time_scheme: runge_kutta
  #kind_time_scheme: explicit_euler

  # constant timestep (s) for innerr loop in usteady computation
  # valid when kind_time_determine: dt
  timestep_constant: 1.0

  # Temporal accuracy using LUSGS unsteady simulation
  # --2nd_backward_diff or 1st_backward_diff
  kind_backward_difference: 2nd_backward_diff
  #kind_backward_difference: 1st_backward_diff


restart_process:

  # Output directory
  directory_output: output_restart

  # Time series
  # --True: stored individually as time series, False: stored by overwriting
  flag_time_series: False

  # Digid for step
  # --for example, restart_0012.dat will be stored if using digid_step: 4
  digid_step: 4

  # Restart step for reading
  restart_step: 500

  # Restart file name (output)
  file_restart: restart.dat

  # Output frequency
  frequency_output: 1


post_process:
  # Output directory
  directory_output: output_result

  # Output (GPX)
  flag_output_gpx: True
  filename_output_gpx: geodetic.gpx

  # Output (KML)
  kml:
    flag_output: True
    # File name
    filename_output: geodetic.kml
    # --kml parameters
    linestyle_color: simplekml.Color.white
    linestyle_width: 4
    extrude: 1
    # --Output frequency
    frequency_output: 10

  # Output (Tecplot)  
  tecplot:
    flag_output: True
    # File name
    filename_output: tecplot.dat
    # --Output frequency
    frequency_output: 1

  # Output (VTK)  
  flag_output_vtk: False
  filename_output_vtk: output.vtk



# Monte-Carlo process
montecarlo:
  # TAcode case directory
  work_dir: work_montecarlo
  case_dir: case
  
  # Template path for Tacode work directory
  template_path_specify: default # default or manual
  template_path: ../testcase_template 

  # Target variables to be changed in the Monte Carlo routine
  target_variable:
    - 
      - density_factor # Variable name
      - initial_settings # Variable's root name 
      - 0.1          # Dispersion in random
#    - 
#      - velocity # Variable name
#      - initial_settings # Variable's root name 
#      - 0.1          # Dispersion in random

  # Executing script
  #cmd_program: python3.9
  #cmd_log: log_tacode
  #cmd_path_specify: default # default or manual
  #cmd_path: ../../src
  #cmd_tacode: tacode.py
  cmd_shell: ./run_tacode.sh
  
  # Control file
  filename_control: config.yml
  
  # Result file name computed by Tacode
  filename_trajectory: trajectory.dat
  
  # Result trajectory of Tacode 
  result_dir: result_tacode
  flag_tecplot: True
  header_tecplot: variables=Time[day],Longitude[deg],Latitude[deg],Altitude[km],Vel_long[m/s],Vel_lat[m/s],Vel_alt[m/s],Vel_mag[m/s],Density[kg/m3],Temperature[K],Kn,Time[sec]
  filename_tecplot: tecplot_taresult.dat

