#!/usr/bin/env python3
#
# Apollo 4（AS-501）の飛行データを SI 単位の参照ファイルに直す。
#
# 出所:
#   [1] R. C. Ried, Jr., W. C. Rochelle, J. D. Milhoan,
#       "Radiative Heating to the Apollo Command Module: Engineering Prediction and
#        Flight Measurement", NASA TM X-58091, April 1972.
#       **Table I. Apollo 4 trajectory (45-day best estimated trajectory, 12/20/67)**
#       -> 時刻・高度・対地速度・よどみ圧・自由流密度・非断熱係数・対流加熱
#   [2] 同 figure 22 の放射計データ（Apollo 4 radiometer CA3363K）を
#       WebPlotDigitizer で読み取ったもの -> 放射加熱
#
# 入力は参照ディレクトリ（既定 ../../../references/20260423_Apollo_radiation）に
# 置いてある、ユーザーが手作業で抽出した 2 ファイル:
#
#   data/ConvectiveHeat/trajectory_apollo4_usunit.dat  … [1] の Table I（ヤード・ポンド法のまま）
#   data/RadiativeHeat/data.csv                        … [2] の読み取り値
#
# **参照ディレクトリはリポジトリの外にある**ので、変換した結果
# （reference/apollo4_flight.dat）をリポジトリに置く。検証はそれだけで再現できる。
#
# 注意（比較するときに効く）:
#   - Table I の加熱は **よどみ点ではなく S/R = 0.732**（放射計 CA3363K の位置、
#     迎角 24.4 度でのよどみ域）での**冷壁**値。よどみ点の相関式と比べるときは
#     分布比（1 ではない）の分だけずれる
#   - 対流加熱は「計算値」、放射加熱は「計測値」。密度も圧力計測から導いた値で、
#     直接の計測量ではない
#   - Table I の 2 行目は元表（OCR）の時刻が "28 970" になっている。前後（29 968 →
#     29 984）と高度の落ち方から **29 970 の誤植**と判断して採用する。高度差
#     8 679 ft を速度 35 220 ft/s で割ると経路角 -6.9 度になり、他の行と整合する

import argparse
import csv
import os
import sys

import numpy as np


# 単位変換
FT_TO_M           = 0.3048
FT_S_TO_M_S       = 0.3048
BTU_FT2_S_TO_W_M2 = 11356.526        # Btu(IT)/(ft^2 s) -> W/m^2
LB_FT3_TO_KG_M3   = 16.01846337396   # lb/ft^3 -> kg/m^3
PSI_TO_PA         = 6894.757293      # psia -> Pa

# Table I の 2 行目の時刻（元表の "28 970" は誤植。上の注意を参照）
TIME_TYPO_ORIGINAL = 28970.0
TIME_TYPO_CORRECTED = 29970.0


def read_table_flight(filename):
  # Table I（ヤード・ポンド法）を読む。'#' で始まる行は誤植の行なので、
  # 時刻だけ直して採る（捨てない。突入直後の経路角はこの行が決める）
  time_list         = []
  altitude_list     = []
  velocity_list     = []
  pressure_list     = []
  density_list      = []
  nonadiabatic_list = []
  heating_list      = []

  def to_float(word):
    try:
      return float(word)
    except ValueError:
      return np.nan

  line_list = []
  with open(filename) as f:
    for line in f:
      stripped = line.strip()
      if len(stripped) == 0 :
        continue
      line_list.append(stripped.lstrip('#'))

  reader = csv.DictReader(line_list)
  for row in reader:
    time_tmp = to_float(row['Time_sec'])
    if time_tmp == TIME_TYPO_ORIGINAL :
      time_tmp = TIME_TYPO_CORRECTED
    time_list.append(time_tmp)
    altitude_list.append(to_float(row['Altitude_ft']))
    velocity_list.append(to_float(row['Relative_velocity_ft_s']))
    pressure_list.append(to_float(row['Stagnation_pressure_psia']))
    density_list.append(to_float(row['Free_stream_density_lb_ft3']))
    nonadiabatic_list.append(to_float(row['Nonadiabatic_factor']))
    heating_list.append(to_float(row['Convective_heating_Btu_ft2_s']))

  table = {
    'time':         np.array(time_list),
    'altitude':     np.array(altitude_list)*FT_TO_M*1.0e-3,
    'velocity':     np.array(velocity_list)*FT_S_TO_M_S,
    'pressure':     np.array(pressure_list)*PSI_TO_PA,
    'density':      np.array(density_list)*LB_FT3_TO_KG_M3,
    'nonadiabatic': np.array(nonadiabatic_list),
    'convective':   np.array(heating_list)*BTU_FT2_S_TO_W_M2,
  }

  order = np.argsort(table['time'])
  for key in table:
    table[key] = table[key][order]

  return table


def read_radiometer(filename):
  # 放射計の読み取り値（時刻 [s], 加熱率 [Btu/ft^2/s]）。行順はソートされていない
  data = np.loadtxt(filename, delimiter=",", comments="#", skiprows=2)
  time_rad    = data[:,0]
  heating_rad = data[:,1]*BTU_FT2_S_TO_W_M2
  order = np.argsort(time_rad)
  return time_rad[order], heating_rad[order]


def write_reference(filename, table, time_rad, heating_rad):
  # 放射加熱を Table I の時刻へ内挿する。表の外は 0（放射が有意なのは
  # 30 050-30 090 s の間だけで、その外は計測そのものが無い）
  heating_rad_interp = np.interp(table['time'], time_rad, heating_rad, left=0.0, right=0.0)

  with open(filename, 'w') as f:
    f.write('# Apollo 4 (AS-501) entry, flight data in SI units\n')
    f.write('# --Source: NASA TM X-58091 (Ried, Rochelle, Milhoan, 1972), Table I,\n')
    f.write('#   and the radiometer CA3363K data of figure 22 (digitised).\n')
    f.write('# --Time is seconds from lift-off (1967-11-09 12:00:01 UTC).\n')
    f.write('# --The heating is the cold-wall value at S/R = 0.732 (the radiometer\n')
    f.write('#   location in the stagnation region at 24.4 deg. angle of attack),\n')
    f.write('#   not at the stagnation point.\n')
    f.write('# --The convective heating and the free-stream density are values derived\n')
    f.write('#   in the reference; the radiative heating is the flight measurement.\n')
    f.write('# --Generated by validation/apollo4/make_reference.py\n')
    f.write('Variables = Time[s],Alti[km],VelrelAbs[m/s],Dens[kg/m3],Pstag[Pa],'
            'Nonadiabatic,Qconv[W/m2],Qrad[W/m2]\n')
    f.write('zone t="Apollo 4 flight" i= {:d} f=point\n'.format(len(table['time'])))
    for n in range(0, len(table['time'])):
      f.write('{:15.7e}{:15.7e}{:15.7e}{:15.7e}{:15.7e}{:15.7e}{:15.7e}{:15.7e}\n'.format(
              table['time'][n], table['altitude'][n], table['velocity'][n],
              np.nan_to_num(table['density'][n]), np.nan_to_num(table['pressure'][n]),
              np.nan_to_num(table['nonadiabatic'][n], nan=1.0),
              table['convective'][n], heating_rad_interp[n]))

  print('Reference file written:', filename)


def main():
  directory_script = os.path.dirname(os.path.realpath(__file__))
  directory_default = os.path.join(directory_script, '../../../references/20260423_Apollo_radiation')

  parser = argparse.ArgumentParser()
  parser.add_argument('--reference-directory', type=str, default=directory_default,
                      help='Directory holding the digitised flight data (outside the repository)')
  parser.add_argument('-o', '--output', type=str,
                      default=os.path.join(directory_script, 'reference/apollo4_flight.dat'))
  args = parser.parse_args()

  file_trajectory = os.path.join(args.reference_directory, 'data/ConvectiveHeat/trajectory_apollo4_usunit.dat')
  file_radiometer = os.path.join(args.reference_directory, 'data/RadiativeHeat/data.csv')

  for filename in [file_trajectory, file_radiometer]:
    if not os.path.exists(filename) :
      print('Flight data not found:', filename)
      print('--Give the directory which holds it with --reference-directory.')
      print('Program stopped.')
      sys.exit(1)

  table = read_table_flight(file_trajectory)
  time_rad, heating_rad = read_radiometer(file_radiometer)

  print('Flight table : {:d} points, {:.0f} to {:.0f} s'.format(
        len(table['time']), table['time'][0], table['time'][-1]))
  print('Radiometer   : {:d} points, {:.0f} to {:.0f} s'.format(
        len(time_rad), time_rad[0], time_rad[-1]))

  write_reference(args.output, table, time_rad, heating_rad)

  # 突入時の状態量（config.yml の初期条件はここから作る）
  print_entry_state(table)

  return


def print_entry_state(table):
  # 最初の 3 点を 2 次で通し、t0 での高度変化率から経路角を出す
  time     = table['time'][0:3]
  altitude = table['altitude'][0:3]*1.0e3
  coefficient = np.polyfit(time - time[0], altitude, 2)
  rate_altitude = coefficient[1]
  velocity = table['velocity'][0]
  angle_path = np.degrees(np.arcsin(rate_altitude/velocity))

  print('')
  print('Entry state (the first point of the table):')
  print('--Time                : {:.0f} s from lift-off'.format(table['time'][0]))
  print('--Altitude            : {:.4f} km'.format(table['altitude'][0]))
  print('--Relative velocity   : {:.2f} m/s'.format(velocity))
  print('--Altitude rate       : {:.2f} m/s (quadratic through the first three points)'.format(rate_altitude))
  print('--Flight-path angle   : {:.3f} deg.'.format(angle_path))

  return


if __name__ == '__main__':
  main()
